import java.time.Instant
import java.util.Date
import java.util.UUID

/*
Note: Data Classes are great for ease-of-use and autogenerated helpers, but there is one key downside:

If you want to have data properties that are internally generated and hidden from default or custom
constructors, you can run into undesirable behaviors. For example if we make the id/date fields
private below, we unfortunately miss out on having them included in all autogenerated helpers. This
can also affect object destructuring and the common componentN() convention features. We can at least
make them immutable and ensure they're only set on initial object creation, but consumers can still set
them explicitly if desired, which may be risky for controlling field value generation and data validity.
*/

data class ServiceResult(
    val id: UUID = UUID.randomUUID(),
    val date: Date = Date.from(Instant.now()),
    val message: String? = null
)